name: Dart

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - uses: subosito/flutter-action@v1.4.0
      - run: flutter pub get
      - run: flutter build apk --debug

      - uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/app/outputs/flutter-apk/app-debug.apk
          asset_name: app-debug-${{ github.ref }}.apk
          tag: ${{ github.ref }}
          overwrite: true
          body: "App debug"
